import { useEffect } from "react";
import { useQuery,useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import type { Tables } from "@/integrations/supabase/types";
export type AuctionState=Tables<"auction_state">&{bidding_open?:boolean};export type Player=Tables<"players">&{phone_number?:string|null;team_name?:string|null;experience?:string|null;submitted_at?:string|null};export type Ambassador=Tables<"ambassadors">;export type AuctionEvent=Tables<"auction_events">;
export function useAuctionState(){return useQuery({queryKey:["auction_state"],queryFn:async()=>{const{data,error}=await supabase.from("auction_state").select("*").eq("id",1).maybeSingle();if(error)throw error;return data as AuctionState|null}})}
export function useMyRoster(userId?:string){return useQuery({queryKey:["my_roster",userId],enabled:!!userId,queryFn:async()=>{const{data,error}=await supabase.from("players").select("*").eq("status","sold").order("sold_at",{ascending:false});if(error)throw error;return data??[]}})}
export function usePublicPlayers(){return useQuery({queryKey:["auction_players_public"],queryFn:async()=>{const{data,error}=await(supabase as any).from("auction_players_public").select("*").order("created_at",{ascending:true});if(error)throw error;return data??[]}})}
export function usePlayers(){return useQuery({queryKey:["players"],queryFn:async()=>{const{data,error}=await supabase.from("players").select("*").order("created_at",{ascending:true});if(error)throw error;return(data??[]) as Player[]}})}
export function usePublicTeams(){return useQuery({queryKey:["auction_teams_public"],queryFn:async()=>{const{data,error}=await(supabase as any).from("auction_teams_public").select("id, team_name, ambassador_name").order("team_name");if(error)throw error;return data??[]}})}
export function useAmbassadors(){return useQuery({queryKey:["ambassadors"],queryFn:async()=>{const{data,error}=await supabase.from("ambassadors").select("*").order("remaining_points",{ascending:false});if(error)throw error;return(data??[]) as Ambassador[]}})}
export function useBids(limit=100){return useQuery({queryKey:["bids",limit],queryFn:async()=>{const{data,error}=await supabase.from("bids").select("*").order("created_at",{ascending:false}).limit(limit);if(error)throw error;return data??[]}})}
export function useAuctionEvents(limit=25){return useQuery({queryKey:["auction_events",limit],queryFn:async()=>{const{data,error}=await supabase.from("auction_events").select("*").order("created_at",{ascending:false}).limit(limit);if(error)throw error;return(data??[]) as AuctionEvent[]}})}
export function useRealtimeAuction(){const qc=useQueryClient();useEffect(()=>{const invalidate=()=>{qc.invalidateQueries({queryKey:["auction_state"]});qc.invalidateQueries({queryKey:["players"]});qc.invalidateQueries({queryKey:["auction_players_public"]});qc.invalidateQueries({queryKey:["auction_teams_public"]});qc.invalidateQueries({queryKey:["ambassadors"]});qc.invalidateQueries({queryKey:["auction_events"]});qc.invalidateQueries({queryKey:["bids"]})};const channel=supabase.channel("auction-sync").on("postgres_changes",{event:"*",schema:"public",table:"auction_state"},invalidate).on("postgres_changes",{event:"*",schema:"public",table:"players"},invalidate).on("postgres_changes",{event:"*",schema:"public",table:"ambassadors"},invalidate).on("postgres_changes",{event:"*",schema:"public",table:"bids"},invalidate).on("postgres_changes",{event:"*",schema:"public",table:"auction_events"},invalidate).subscribe();const onVisible=()=>{if(document.visibilityState==="visible")invalidate()};document.addEventListener("visibilitychange",onVisible);window.addEventListener("online",invalidate);return()=>{supabase.removeChannel(channel);document.removeEventListener("visibilitychange",onVisible);window.removeEventListener("online",invalidate)}},[qc])}
export function minimumNextBid(state:AuctionState|null|undefined){if(!state)return 0;return state.current_bid===null?state.base_price:state.current_bid+state.min_increment}
