import { Link } from "@tanstack/react-router";
import { useAuth } from "@/lib/auth";

export function DashboardShell({ title, subtitle, nav, children }: { title: string; subtitle?: string; nav: { to: string; label: string }[]; children: React.ReactNode; }) {
  const { username, signOut } = useAuth();
  return <main className="mx-auto min-h-[calc(100vh-56px)] max-w-7xl px-4 py-6 sm:px-6"><div className="mb-6 flex flex-col gap-4 border-b border-line pb-5 md:flex-row md:items-end"><div><div className="label-cond text-[11px] text-gold">BIDX AUCTION</div><h1 className="mt-1 font-display text-4xl tracking-wide md:text-5xl">{title}</h1>{subtitle && <p className="mt-1 max-w-2xl text-sm text-mut">{subtitle}</p>}</div><div className="md:ml-auto flex items-center gap-3"><span className="font-mono text-xs text-mut">{username ?? "ACCOUNT"}</span><button onClick={() => void signOut()} className="label-cond border border-line px-3 py-2 text-[11px] hover:border-gold hover:text-gold">Logout</button></div></div><nav className="mb-6 flex gap-2 overflow-x-auto pb-1">{nav.map((item) => <Link key={item.to} to={item.to} activeProps={{ className: "border-gold bg-gold/10 text-gold" }} className="label-cond shrink-0 border border-line bg-panel px-3 py-2 text-[11px] text-mut hover:text-foreground">{item.label}</Link>)}</nav>{children}</main>;
}
export function StatCard({ label, value, detail }: { label: string; value: React.ReactNode; detail?: React.ReactNode }) { return <div className="rounded-2xl border border-line bg-panel p-4 shadow-[0_12px_50px_rgba(0,0,0,.16)]"><div className="label-cond text-[10px] text-mut">{label}</div><div className="mt-2 font-display text-3xl tracking-wide">{value}</div>{detail && <div className="mt-1 text-xs text-mut">{detail}</div>}</div>; }
export const ambassadorNav=[{to:"/ambassador/dashboard",label:"Home"},{to:"/ambassador/live-auction",label:"Live Auction"},{to:"/ambassador/roster",label:"My Roster"},{to:"/ambassador/points",label:"Points"},{to:"/ambassador/profile",label:"Profile"},{to:"/ambassador/notifications",label:"Notifications"},{to:"/ambassador/settings",label:"Settings"}];
export const casterNav=[{to:"/caster/dashboard",label:"Home"},{to:"/caster/auction-control",label:"Auction Control"},{to:"/caster/broadcast",label:"Broadcast View"},{to:"/caster/profile",label:"Profile"},{to:"/caster/settings",label:"Settings"}];
export const adminNav=[{to:"/admin/dashboard",label:"Dashboard"},{to:"/admin/players",label:"Players"},{to:"/admin/ambassadors",label:"Ambassadors"},{to:"/admin/caster",label:"Caster"},{to:"/admin/auction",label:"Auction"},{to:"/admin/live-monitor",label:"Live Monitor"},{to:"/admin/bid-history",label:"Bid History"},{to:"/admin/sales",label:"Sales"},{to:"/admin/settings",label:"Settings"}];
