import { useEffect, useRef, useState } from "react";
import { supabase } from "@/integrations/supabase/client";

const ROOM = "bidx-auction-live";
const CASTER = "caster";
const makeId = () => `viewer-${crypto.randomUUID()}`;
function sendSignal(signal: { room_id: string; sender_id: string; target_id: string; signal_type: string; payload: unknown }) { return (supabase as any).from("webrtc_signals").insert(signal); }

export function CasterCamera({ live }: { live: boolean }) {
  const videoRef=useRef<HTMLVideoElement>(null), streamRef=useRef<MediaStream|null>(null), peers=useRef(new Map<string,RTCPeerConnection>());
  const [error,setError]=useState<string|null>(null);
  useEffect(()=>{ if(!live){peers.current.forEach(p=>p.close());peers.current.clear();streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;if(videoRef.current)videoRef.current.srcObject=null;return;} let cancelled=false;
    const start=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});if(cancelled)return stream.getTracks().forEach(t=>t.stop());streamRef.current=stream;if(videoRef.current)videoRef.current.srcObject=stream;setError(null);}catch(e){setError(e instanceof Error?e.message:"Camera/microphone permission denied");}};void start();return()=>{cancelled=true;};
  },[live]);
  useEffect(()=>{if(!live)return;const channel=supabase.channel("bidx-webrtc-caster").on("postgres_changes",{event:"INSERT",schema:"public",table:"webrtc_signals",filter:"target_id=eq.caster"},async({new:raw})=>{const s=raw as any;if(s.room_id!==ROOM||s.signal_type!=="join"||!streamRef.current)return;const viewer=s.sender_id as string;peers.current.get(viewer)?.close();const pc=new RTCPeerConnection({iceServers:[{urls:"stun:stun.l.google.com:19302"}]});peers.current.set(viewer,pc);streamRef.current.getTracks().forEach(t=>pc.addTrack(t,streamRef.current!));pc.onicecandidate=e=>{if(e.candidate)void sendSignal({room_id:ROOM,sender_id:CASTER,target_id:viewer,signal_type:"ice",payload:e.candidate.toJSON()});};const offer=await pc.createOffer();await pc.setLocalDescription(offer);await sendSignal({room_id:ROOM,sender_id:CASTER,target_id:viewer,signal_type:"offer",payload:offer});}).on("postgres_changes",{event:"INSERT",schema:"public",table:"webrtc_signals",filter:"target_id=eq.caster"},async({new:raw})=>{const s=raw as any;if(s.room_id!==ROOM)return;const pc=peers.current.get(s.sender_id);if(!pc)return;if(s.signal_type==="answer")await pc.setRemoteDescription(s.payload);if(s.signal_type==="ice")await pc.addIceCandidate(s.payload).catch(()=>undefined);}).subscribe();return()=>{void supabase.removeChannel(channel);peers.current.forEach(p=>p.close());peers.current.clear();};},[live]);
  return <div className="relative aspect-video overflow-hidden rounded-2xl border border-line bg-black"><video ref={videoRef} autoPlay muted playsInline className="absolute inset-0 h-full w-full object-cover"/>{!live&&<Offline label="Caster camera offline"/>}{error&&<div className="absolute inset-x-0 bottom-0 bg-alert/90 p-3 text-xs">{error}</div>}{live&&<span className="absolute left-3 top-3 rounded-full border border-red-400/30 bg-black/60 px-3 py-1 font-mono text-[10px] text-red-300">● LIVE</span>}</div>;
}
export function AudienceCaster({ live }: { live: boolean }) {
  const videoRef=useRef<HTMLVideoElement>(null), viewerId=useRef(makeId()), pcRef=useRef<RTCPeerConnection|null>(null);const [connected,setConnected]=useState(false);const [error,setError]=useState<string|null>(null);
  useEffect(()=>{if(!live){pcRef.current?.close();pcRef.current=null;setConnected(false);return;}const id=viewerId.current;let channel:ReturnType<typeof supabase.channel>|null=null;const join=async()=>{await sendSignal({room_id:ROOM,sender_id:id,target_id:CASTER,signal_type:"join",payload:{}})};const start=async()=>{channel=supabase.channel(`bidx-webrtc-${id}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"webrtc_signals",filter:`target_id=eq.${id}`},async({new:raw})=>{const s=raw as any;if(s.room_id!==ROOM)return;if(s.signal_type==="offer"){pcRef.current?.close();const pc=new RTCPeerConnection({iceServers:[{urls:"stun:stun.l.google.com:19302"}]});pcRef.current=pc;pc.ontrack=e=>{if(videoRef.current)videoRef.current.srcObject=e.streams[0];setConnected(true)};pc.onicecandidate=e=>{if(e.candidate)void sendSignal({room_id:ROOM,sender_id:id,target_id:CASTER,signal_type:"ice",payload:e.candidate.toJSON()})};await pc.setRemoteDescription(s.payload);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await sendSignal({room_id:ROOM,sender_id:id,target_id:CASTER,signal_type:"answer",payload:answer});}else if(s.signal_type==="ice"&&pcRef.current)await pcRef.current.addIceCandidate(s.payload).catch(()=>undefined)}).subscribe(async status=>{if(status==="SUBSCRIBED")await join()});};void start().catch(e=>setError(e instanceof Error?e.message:"Unable to connect to caster"));return()=>{if(channel)void supabase.removeChannel(channel);pcRef.current?.close();pcRef.current=null;setConnected(false)}},[live]);
  return <div className="relative aspect-video min-h-[220px] overflow-hidden rounded-2xl border border-line bg-black"><video ref={videoRef} autoPlay playsInline controls={false} className="absolute inset-0 h-full w-full object-cover"/>{!connected&&<Offline label={live?"Waiting for caster connection…":"Caster Offline"}/>} {error&&<div className="absolute inset-x-0 bottom-0 bg-alert/90 p-3 text-xs">{error}</div>}</div>;
}
function Offline({label}:{label:string}){return <div className="absolute inset-0 grid place-items-center"><div className="text-center"><div className="label-cond text-sm text-mut">{label}</div><div className="mt-1 text-xs text-mut/60">Waiting for the live feed…</div></div></div>}
