/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AmbassadorRouteImport } from './routes/ambassador'
import { Route as AuctionRouteImport } from './routes/auction'
import { Route as BroadcastRouteImport } from './routes/broadcast'
import { Route as CasterRouteImport } from './routes/caster'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyPlayerRouteImport } from './routes/my-player'
import { Route as AdminLiveMonitorRouteImport } from './routes/admin_.live-monitor'
import { Route as AmbassadorLiveAuctionRouteImport } from './routes/ambassador_.live-auction'
import { Route as CasterAuctionControlRouteImport } from './routes/caster_.auction-control'
import { Route as CasterCheckRouteImport } from './routes/caster_.check'
import { Route as PlayerRegisterRouteImport } from './routes/player/register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbassadorRoute = AmbassadorRouteImport.update({
  id: '/ambassador',
  path: '/ambassador',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionRoute = AuctionRouteImport.update({
  id: '/auction',
  path: '/auction',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadcastRoute = BroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => rootRouteImport,
} as any)
const CasterRoute = CasterRouteImport.update({
  id: '/caster',
  path: '/caster',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPlayerRoute = MyPlayerRouteImport.update({
  id: '/my-player',
  path: '/my-player',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLiveMonitorRoute = AdminLiveMonitorRouteImport.update({
  id: '/admin_/live-monitor',
  path: '/admin/live-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbassadorLiveAuctionRoute = AmbassadorLiveAuctionRouteImport.update({
  id: '/ambassador_/live-auction',
  path: '/ambassador/live-auction',
  getParentRoute: () => rootRouteImport,
} as any)
const CasterAuctionControlRoute = CasterAuctionControlRouteImport.update({
  id: '/caster_/auction-control',
  path: '/caster/auction-control',
  getParentRoute: () => rootRouteImport,
} as any)
const CasterCheckRoute = CasterCheckRouteImport.update({
  id: '/caster_/check',
  path: '/caster/check',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRegisterRoute = PlayerRegisterRouteImport.update({
  id: '/player/register',
  path: '/player/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ambassador': typeof AmbassadorRoute
  '/auction': typeof AuctionRoute
  '/broadcast': typeof BroadcastRoute
  '/caster': typeof CasterRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/my-player': typeof MyPlayerRoute
  '/admin/live-monitor': typeof AdminLiveMonitorRoute
  '/ambassador/live-auction': typeof AmbassadorLiveAuctionRoute
  '/caster/auction-control': typeof CasterAuctionControlRoute
  '/caster/check': typeof CasterCheckRoute
  '/player/register': typeof PlayerRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ambassador': typeof AmbassadorRoute
  '/auction': typeof AuctionRoute
  '/broadcast': typeof BroadcastRoute
  '/caster': typeof CasterRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/my-player': typeof MyPlayerRoute
  '/admin/live-monitor': typeof AdminLiveMonitorRoute
  '/ambassador/live-auction': typeof AmbassadorLiveAuctionRoute
  '/caster/auction-control': typeof CasterAuctionControlRoute
  '/caster/check': typeof CasterCheckRoute
  '/player/register': typeof PlayerRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ambassador': typeof AmbassadorRoute
  '/auction': typeof AuctionRoute
  '/broadcast': typeof BroadcastRoute
  '/caster': typeof CasterRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/my-player': typeof MyPlayerRoute
  '/admin_/live-monitor': typeof AdminLiveMonitorRoute
  '/ambassador_/live-auction': typeof AmbassadorLiveAuctionRoute
  '/caster_/auction-control': typeof CasterAuctionControlRoute
  '/caster_/check': typeof CasterCheckRoute
  '/player/register': typeof PlayerRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ambassador'
    | '/auction'
    | '/broadcast'
    | '/caster'
    | '/change-password'
    | '/login'
    | '/my-player'
    | '/admin/live-monitor'
    | '/ambassador/live-auction'
    | '/caster/auction-control'
    | '/caster/check'
    | '/player/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ambassador'
    | '/auction'
    | '/broadcast'
    | '/caster'
    | '/change-password'
    | '/login'
    | '/my-player'
    | '/admin/live-monitor'
    | '/ambassador/live-auction'
    | '/caster/auction-control'
    | '/caster/check'
    | '/player/register'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ambassador'
    | '/auction'
    | '/broadcast'
    | '/caster'
    | '/change-password'
    | '/login'
    | '/my-player'
    | '/admin_/live-monitor'
    | '/ambassador_/live-auction'
    | '/caster_/auction-control'
    | '/caster_/check'
    | '/player/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AmbassadorRoute: typeof AmbassadorRoute
  AuctionRoute: typeof AuctionRoute
  BroadcastRoute: typeof BroadcastRoute
  CasterRoute: typeof CasterRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  MyPlayerRoute: typeof MyPlayerRoute
  AdminLiveMonitorRoute: typeof AdminLiveMonitorRoute
  AmbassadorLiveAuctionRoute: typeof AmbassadorLiveAuctionRoute
  CasterAuctionControlRoute: typeof CasterAuctionControlRoute
  CasterCheckRoute: typeof CasterCheckRoute
  PlayerRegisterRoute: typeof PlayerRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambassador': {
      id: '/ambassador'
      path: '/ambassador'
      fullPath: '/ambassador'
      preLoaderRoute: typeof AmbassadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction': {
      id: '/auction'
      path: '/auction'
      fullPath: '/auction'
      preLoaderRoute: typeof AuctionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcast': {
      id: '/broadcast'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof BroadcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caster': {
      id: '/caster'
      path: '/caster'
      fullPath: '/caster'
      preLoaderRoute: typeof CasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-player': {
      id: '/my-player'
      path: '/my-player'
      fullPath: '/my-player'
      preLoaderRoute: typeof MyPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/live-monitor': {
      id: '/admin_/live-monitor'
      path: '/admin/live-monitor'
      fullPath: '/admin/live-monitor'
      preLoaderRoute: typeof AdminLiveMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambassador_/live-auction': {
      id: '/ambassador_/live-auction'
      path: '/ambassador/live-auction'
      fullPath: '/ambassador/live-auction'
      preLoaderRoute: typeof AmbassadorLiveAuctionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caster_/auction-control': {
      id: '/caster_/auction-control'
      path: '/caster/auction-control'
      fullPath: '/caster/auction-control'
      preLoaderRoute: typeof CasterAuctionControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caster_/check': {
      id: '/caster_/check'
      path: '/caster/check'
      fullPath: '/caster/check'
      preLoaderRoute: typeof CasterCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/register': {
      id: '/player/register'
      path: '/player/register'
      fullPath: '/player/register'
      preLoaderRoute: typeof PlayerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AmbassadorRoute: AmbassadorRoute,
  AuctionRoute: AuctionRoute,
  BroadcastRoute: BroadcastRoute,
  CasterRoute: CasterRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  MyPlayerRoute: MyPlayerRoute,
  AdminLiveMonitorRoute: AdminLiveMonitorRoute,
  AmbassadorLiveAuctionRoute: AmbassadorLiveAuctionRoute,
  CasterAuctionControlRoute: CasterAuctionControlRoute,
  CasterCheckRoute: CasterCheckRoute,
  PlayerRegisterRoute: PlayerRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
